sudo: false

language: node_js
node_js:
- "node"

os:
  - linux
  - osx

services:
  - xvfb

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent
  - codecov -f out/coverage/coverage-final.json